version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
      size: large
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run: powershell.exe -File rinne.ps1
      - run: ping -t localhost
          
